### ISSUE TITLE
Migration to WebApps WG: Implementor interest?

### ISSUE THREAD

**Issue by LJWatson** [WICG/page-lifecycle#28]
This specification has been proposed for migration to the [WebApps WG](https://w3c.github.io/charter-drafts/webapps-2019) (which is expected to partly replace the WebPlat WG). For this to happen, we need expressions of interest/intent to commit from at least two implementors.

Please let us know if you plan to implement this specification, or if you can point to any publicly documented expressions of interest from implementors.

The draft WebApps charter will go to the Advisory Committee (AC) within the next two or three weeks, so quick responses may make the difference.

@Chaals @marcoscaceres

**Comment by domenic** [comment]
@smaug---- has been pretty engaged from Gecko IIRC so could maybe speak to implementation plans. However, given that this spec consists mostly of patches to HTML, it would probably be best to graduate from incubation as just a HTML pull request, instead of a HTML pull request that references a separate spec whose non-boilerplate contents are a couple definitions, one 2-step algorithm, and one 4-step algorithm.

**Comment by marcoscaceres** [comment]
Thanks, @domenic. That’s really useful info. Make sense then to not make it a candidate for WebApps WG. 

I’ll wait to hear from @smaug---- about our plans and then maybe we can consider graduating it to the WHATWG when ready. No hurry tho :)

**Comment by LJWatson** [comment]
Ping @dmurph and @inexorabletash for comments.

**Comment by domenic** [comment]
Closing as it seems the path forward is integration into the HTML spec.
